[conf]
    host = "172.107.1.2"
    user = "root"
    pass = "123456"
    db   = "subscan"
[api]
	dsn = "?readTimeout=2s&writeTimeout=3s&parseTime=true&loc=Local&charset=utf8mb4,utf8"
[task]
    dsn = "?parseTime=true&loc=Local&charset=utf8mb4,utf8"
[test]
    dsn = "root:@tcp(127.0.0.1)/subscan_test?parseTime=true&loc=Local&charset=utf8mb4,utf8"